import { STREAM_ROWS, type StreamTitle } from "./types.ts";

function ia(id: string, file: string) {
  return `https://archive.org/download/${id}/${encodeURIComponent(file)}`;
}
function thumb(id: string) {
  return `https://archive.org/services/img/${id}`;
}
function embed(id: string) {
  return `https://archive.org/embed/${id}`;
}

export const STREAM_CATALOG: StreamTitle[] = [
  {
    id: "night-shift",
    title: "Night Shift",
    tagline: "The booth sees everything.",
    synopsis:
      "A night-shift parking attendant witnesses a drop that was never meant to have a witness. CINEMA Original — watch the locked director's animatic, built on the Script-to-Screen floor from the shooting script.",
    year: 2026,
    runtimeMin: 8,
    rating: "PG-13",
    kind: "animatic",
    origin: "original",
    genres: ["neo-noir", "thriller", "short"],
    director: "CINEMA",
    cast: ["Mara", "Cole", "Driver"],
    poster: "/stream/night-shift-poster.jpg",
    backdrop: "/stream/night-shift-backdrop.jpg",
    trailer: "/stream/night-shift-teaser.mp4",
    player: "animatic",
    animaticJobId: "job_night_shift",
    featured: true,
    badge: "Original",
    collections: ["originals", "trending", "noir", "tonight", "new"],
  },
  {
    id: "last-reel",
    title: "The Last Reel",
    tagline: "The film outside is still being shot.",
    synopsis:
      "A projectionist in a dying seaside cinema finds a reel that was never catalogued. CINEMA Original — in production on the floor. Teaser now; feature lock forthcoming.",
    year: 2026,
    runtimeMin: 12,
    rating: "PG-13",
    kind: "film",
    origin: "original",
    genres: ["mystery", "drama"],
    director: "CINEMA",
    cast: [],
    poster: "/stream/last-reel-poster.jpg",
    backdrop: "/stream/last-reel-backdrop.jpg",
    trailer: "/stream/night-shift-teaser.mp4",
    player: "video",
    comingSoon: true,
    badge: "Coming soon",
    collections: ["originals", "new"],
  },
  {
    id: "sodium",
    title: "Sodium",
    tagline: "The city after the lamps take over.",
    synopsis:
      "A cine-poem of American night, photographed only by sodium-vapor light. CINEMA Original in development — a lookbook first, a lock later.",
    year: 2026,
    runtimeMin: 18,
    rating: "NR",
    kind: "short",
    origin: "original",
    genres: ["essay", "city"],
    director: "CINEMA",
    cast: [],
    poster: "/stream/sodium-poster.jpg",
    backdrop: "/stream/sodium-backdrop.jpg",
    player: "none",
    comingSoon: true,
    badge: "In development",
    collections: ["originals", "new"],
  },
  {
    id: "wet-down",
    title: "Wet Down",
    tagline: "The street is not wet until we say it is.",
    synopsis:
      "A night-exterior package, observed. CINEMA Original about the labor that makes rain look like cinema. Teaser from the Night Shift unit.",
    year: 2026,
    runtimeMin: 6,
    rating: "PG",
    kind: "short",
    origin: "original",
    genres: ["drama", "industry"],
    director: "CINEMA",
    cast: [],
    poster: "/stream/wet-down-poster.jpg",
    backdrop: "/stream/wet-down-backdrop.jpg",
    trailer: "/stream/night-shift-teaser.mp4",
    playback: "/stream/night-shift-teaser.mp4",
    player: "video",
    badge: "Original",
    collections: ["originals", "shorts", "trending", "new"],
  },
  {
    id: "notld",
    title: "Night of the Living Dead",
    tagline: "They won't stay dead.",
    synopsis:
      "A rural farmhouse becomes the last light in a night of the risen dead. George A. Romero's 1968 landmark entered the public domain when its original release omitted a copyright notice.",
    year: 1968,
    runtimeMin: 96,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["horror", "thriller"],
    director: "George A. Romero",
    cast: ["Duane Jones", "Judith O'Dea", "Karl Hardman"],
    poster: "/stream/notld-backdrop.jpg",
    backdrop: "/stream/notld-backdrop.jpg",
    playback: ia("Night.Of.The.Living.Dead_1080p", "NightOfTheLivingDead_DVD5_512kb.mp4"),
    archiveId: "Night.Of.The.Living.Dead_1080p",
    embedUrl: embed("Night.Of.The.Living.Dead_1080p"),
    player: "video",
    featured: true,
    collections: ["trending", "horror", "classics", "tonight"],
  },
  {
    id: "nosferatu",
    title: "Nosferatu",
    tagline: "A symphony of horror.",
    synopsis:
      "Count Orlok crosses the sea and the shadow of a plague follows. F. W. Murnau's unauthorized Dracula, 1922, is a foundation stone of screen horror and in the U.S. public domain.",
    year: 1922,
    runtimeMin: 94,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["horror", "silent"],
    director: "F. W. Murnau",
    cast: ["Max Schreck", "Greta Schröder", "Gustav von Wangenheim"],
    poster: "/stream/nosferatu-backdrop.jpg",
    backdrop: "/stream/nosferatu-backdrop.jpg",
    playback: ia("Nosferatu1922", "Nosferatu-smaller2.mp4"),
    archiveId: "Nosferatu1922",
    embedUrl: embed("Nosferatu1922"),
    player: "video",
    collections: ["silent", "horror", "classics", "trending", "expressionist"],
  },
  {
    id: "caligari",
    title: "The Cabinet of Dr. Caligari",
    tagline: "You must become Caligari.",
    synopsis:
      "A fairground, a somnambulist, a town bent into painted angles. The 1920 German expressionist film that taught cinema it could look like a mind.",
    year: 1920,
    runtimeMin: 76,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["horror", "silent", "expressionist"],
    director: "Robert Wiene",
    cast: ["Werner Krauss", "Conrad Veidt", "Lil Dagover"],
    poster: thumb("thecabinetofdrcaligari"),
    backdrop: thumb("thecabinetofdrcaligari"),
    playback: ia("thecabinetofdrcaligari", "KabinettDesDoktorCaligariDas_512kb.mp4"),
    archiveId: "thecabinetofdrcaligari",
    embedUrl: embed("thecabinetofdrcaligari"),
    player: "video",
    collections: ["silent", "horror", "classics", "expressionist"],
  },
  {
    id: "charade",
    title: "Charade",
    tagline: "The merriest murder.",
    synopsis:
      "Audrey Hepburn and Cary Grant in Stanley Donen's Paris thriller-comedy. Released in 1963 without a valid copyright notice, it is a public-domain studio picture — rare air.",
    year: 1963,
    runtimeMin: 113,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["romance", "thriller", "comedy"],
    director: "Stanley Donen",
    cast: ["Audrey Hepburn", "Cary Grant", "Walter Matthau"],
    poster: "/stream/charade-backdrop.jpg",
    backdrop: "/stream/charade-backdrop.jpg",
    playback: ia(
      "charade-1963-cary-grant-audrey-hepburn-comedy-mystery-romance-thriller-full-movie",
      "Charade_READY.mp4",
    ),
    archiveId: "charade-1963-cary-grant-audrey-hepburn-comedy-mystery-romance-thriller-full-movie",
    embedUrl: embed("charade-1963-cary-grant-audrey-hepburn-comedy-mystery-romance-thriller-full-movie"),
    player: "video",
    featured: true,
    collections: ["trending", "comedy", "classics", "tonight"],
  },
  {
    id: "carnival",
    title: "Carnival of Souls",
    tagline: "She escaped the river. The rest did not.",
    synopsis:
      "A church organist walks through a world that will not hold her. Herk Harvey's 1962 independent ghost story, shot in Lawrence, Kansas, and now a public-domain cult object.",
    year: 1962,
    runtimeMin: 78,
    rating: "PG",
    kind: "film",
    origin: "public_domain",
    genres: ["horror", "ghost"],
    director: "Herk Harvey",
    cast: ["Candace Hilligoss", "Frances Feist"],
    poster: thumb("CarnivalofSouls"),
    backdrop: thumb("CarnivalofSouls"),
    playback: ia("CarnivalofSouls", "CarnivalOfSouls_512kb.mp4"),
    archiveId: "CarnivalofSouls",
    embedUrl: embed("CarnivalofSouls"),
    player: "video",
    collections: ["horror", "classics", "trending"],
  },
  {
    id: "haunted-hill",
    title: "House on Haunted Hill",
    tagline: "Ten thousand dollars if you last the night.",
    synopsis:
      "Vincent Price offers a fortune to anyone who can survive a night in a charged house. William Castle, 1959 — a carnival pitch that became a public-domain staple.",
    year: 1959,
    runtimeMin: 75,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["horror", "thriller"],
    director: "William Castle",
    cast: ["Vincent Price", "Carol Ohmart", "Richard Long"],
    poster: thumb("HouseOnHauntedHill1959"),
    backdrop: thumb("HouseOnHauntedHill1959"),
    playback: ia("HouseOnHauntedHill1959", "House-On-Haunted-Hill_512kb.mp4"),
    archiveId: "HouseOnHauntedHill1959",
    embedUrl: embed("HouseOnHauntedHill1959"),
    player: "video",
    collections: ["horror", "classics", "tonight"],
  },
  {
    id: "last-man",
    title: "The Last Man on Earth",
    tagline: "Every night they come.",
    synopsis:
      "Vincent Price as the last uninfected man, holding a house against the dusk. The 1964 first screen take on Matheson's I Am Legend, in the public domain.",
    year: 1964,
    runtimeMin: 86,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["horror", "science fiction"],
    director: "Ubaldo Ragona, Sidney Salkow",
    cast: ["Vincent Price", "Franca Bettoia"],
    poster: thumb("TheLastManOnEarth_72"),
    backdrop: thumb("TheLastManOnEarth_72"),
    playback: ia("TheLastManOnEarth_72", "the_last_man_on_earth.mp4"),
    archiveId: "TheLastManOnEarth_72",
    embedUrl: embed("TheLastManOnEarth_72"),
    player: "video",
    collections: ["horror", "classics"],
  },
  {
    id: "white-zombie",
    title: "White Zombie",
    tagline: "Bela Lugosi in Haiti.",
    synopsis:
      "The first feature-length zombie film, 1932. Lugosi as Murder Legendre, a mill of the living dead, and a pre-code atmosphere that never quite resolved.",
    year: 1932,
    runtimeMin: 67,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["horror"],
    director: "Victor Halperin",
    cast: ["Bela Lugosi", "Madge Bellamy", "John Harron"],
    poster: thumb("WhiteZombie1932"),
    backdrop: thumb("WhiteZombie1932"),
    playback: ia("WhiteZombie1932", "WhiteZombie_512kb.mp4"),
    archiveId: "WhiteZombie1932",
    embedUrl: embed("WhiteZombie1932"),
    player: "video",
    collections: ["horror", "classics", "precode"],
  },
  {
    id: "little-shop",
    title: "The Little Shop of Horrors",
    tagline: "Feed me.",
    synopsis:
      "Roger Corman's 1960 black comedy about a florist's assistant and a plant with an appetite. Shot in two days, public domain, and the seed of a later musical that is not.",
    year: 1960,
    runtimeMin: 72,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["comedy", "horror"],
    director: "Roger Corman",
    cast: ["Jonathan Haze", "Jackie Joseph", "Jack Nicholson"],
    poster: thumb("TheLittleShopOfHorrors"),
    backdrop: thumb("TheLittleShopOfHorrors"),
    playback: ia("TheLittleShopOfHorrors", "The Little Shop of Horrors.mp4"),
    archiveId: "TheLittleShopOfHorrors",
    embedUrl: embed("TheLittleShopOfHorrors"),
    player: "video",
    collections: ["comedy", "horror", "classics", "tonight"],
  },
  {
    id: "detour",
    title: "Detour",
    tagline: "A hitch, a dead man, a name that isn't yours.",
    synopsis:
      "Edgar G. Ulmer's 1945 Poverty Row noir, seventy minutes of bad luck on the highway. A pillar of American B-cinema, and in the public domain.",
    year: 1945,
    runtimeMin: 68,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["noir", "crime"],
    director: "Edgar G. Ulmer",
    cast: ["Tom Neal", "Ann Savage"],
    poster: thumb("Detour"),
    backdrop: thumb("Detour"),
    playback: ia("Detour", "Detour_512kb.mp4"),
    archiveId: "Detour",
    embedUrl: embed("Detour"),
    player: "video",
    collections: ["noir", "classics", "trending"],
  },
  {
    id: "hitch-hiker",
    title: "The Hitch-Hiker",
    tagline: "Two men. One gun. Open road.",
    synopsis:
      "Ida Lupino directs 1953: a true-crime noir of two fishermen and the escaped convict they pick up. The first American noir directed by a woman, public domain.",
    year: 1953,
    runtimeMin: 71,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["noir", "thriller"],
    director: "Ida Lupino",
    cast: ["Edmond O'Brien", "Frank Lovejoy", "William Talman"],
    poster: thumb("Hitch_Hiker"),
    backdrop: thumb("Hitch_Hiker"),
    playback: ia("Hitch_Hiker", "Hitch-Hiker_512kb.mp4"),
    archiveId: "Hitch_Hiker",
    embedUrl: embed("Hitch_Hiker"),
    player: "video",
    collections: ["noir", "classics"],
  },
  {
    id: "godfrey",
    title: "My Man Godfrey",
    tagline: "A forgotten man in a Park Avenue hunt.",
    synopsis:
      "William Powell and Carole Lombard, 1936. Screwball with a Depression spine: a scavenger hunt, a butler, a family that cannot see the floor. Public domain.",
    year: 1936,
    runtimeMin: 94,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["comedy", "romance"],
    director: "Gregory La Cava",
    cast: ["William Powell", "Carole Lombard", "Alice Brady"],
    poster: thumb("MyManGodfrey1936"),
    backdrop: thumb("MyManGodfrey1936"),
    playback: ia("MyManGodfrey1936", "MyManGodfrey1936_512kb.mp4"),
    archiveId: "MyManGodfrey1936",
    embedUrl: embed("MyManGodfrey1936"),
    player: "video",
    collections: ["comedy", "classics", "tonight"],
  },
  {
    id: "scarlet-street",
    title: "Scarlet Street",
    tagline: "A cashier, a painting, a lie.",
    synopsis:
      "Fritz Lang, 1945. Edward G. Robinson as a meek cashier whose Sunday paintings become a trap. Noir as humiliation, now in the public domain.",
    year: 1945,
    runtimeMin: 102,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["noir", "drama"],
    director: "Fritz Lang",
    cast: ["Edward G. Robinson", "Joan Bennett", "Dan Duryea"],
    poster: thumb("Scarlet.Street.194517"),
    backdrop: thumb("Scarlet.Street.194517"),
    playback: ia("Scarlet.Street.194517", "ScarletStreet1945.mp4"),
    archiveId: "Scarlet.Street.194517",
    embedUrl: embed("Scarlet.Street.194517"),
    player: "video",
    collections: ["noir", "classics"],
  },
  {
    id: "doa",
    title: "D.O.A.",
    tagline: "A murdered man investigates his own death.",
    synopsis:
      "Rudolph Maté, 1950. Edmund O'Brien walks into a precinct and reports a murder: his. A public-domain noir with a clock already running.",
    year: 1950,
    runtimeMin: 83,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["noir", "thriller"],
    director: "Rudolph Maté",
    cast: ["Edmund O'Brien", "Pamela Britton"],
    poster: thumb("doa-1950_202506"),
    backdrop: thumb("doa-1950_202506"),
    playback: ia("doa-1950_202506", "DOA 1950.ia.mp4"),
    archiveId: "doa-1950_202506",
    embedUrl: embed("doa-1950_202506"),
    player: "video",
    collections: ["noir", "classics", "trending"],
  },
  {
    id: "general",
    title: "The General",
    tagline: "A locomotive, a girl, a war.",
    synopsis:
      "Buster Keaton, 1926. An engineer, a stolen train, and some of the most precise physical comedy ever photographed. U.S. public domain.",
    year: 1926,
    runtimeMin: 79,
    rating: "G",
    kind: "film",
    origin: "public_domain",
    genres: ["comedy", "silent", "action"],
    director: "Buster Keaton, Clyde Bruckman",
    cast: ["Buster Keaton", "Marion Mack"],
    poster: thumb("TheGeneral1926"),
    backdrop: thumb("TheGeneral1926"),
    playback: ia("TheGeneral1926", "The_General_1926_720p_512kb.mp4"),
    archiveId: "TheGeneral1926",
    embedUrl: embed("TheGeneral1926"),
    player: "video",
    collections: ["silent", "comedy", "classics", "trending"],
  },
  {
    id: "sherlock-jr",
    title: "Sherlock Jr.",
    tagline: "He walks into the screen.",
    synopsis:
      "Keaton as a projectionist who dreams himself into the film. 1924, forty-five minutes, and still the cleanest joke cinema has about itself.",
    year: 1924,
    runtimeMin: 45,
    rating: "G",
    kind: "film",
    origin: "public_domain",
    genres: ["comedy", "silent"],
    director: "Buster Keaton",
    cast: ["Buster Keaton", "Kathryn McGuire"],
    poster: thumb("MyMovie_20190318"),
    backdrop: thumb("MyMovie_20190318"),
    playback: ia("MyMovie_20190318", "My Movie.mp4"),
    archiveId: "MyMovie_20190318",
    embedUrl: embed("MyMovie_20190318"),
    player: "video",
    collections: ["silent", "comedy", "classics"],
  },
  {
    id: "steamboat",
    title: "Steamboat Bill, Jr.",
    tagline: "The house falls. He does not.",
    synopsis:
      "Keaton, 1928. A cyclone, a facade, a window that is exactly the size of a man. Public domain, and still dangerous to watch if you build houses.",
    year: 1928,
    runtimeMin: 70,
    rating: "G",
    kind: "film",
    origin: "public_domain",
    genres: ["comedy", "silent"],
    director: "Charles Reisner, Buster Keaton",
    cast: ["Buster Keaton", "Ernest Torrence"],
    poster: thumb("steamboat_bill_ipod"),
    backdrop: thumb("steamboat_bill_ipod"),
    playback: ia("steamboat_bill_ipod", "steamboat_bill_512kb.mp4"),
    archiveId: "steamboat_bill_ipod",
    embedUrl: embed("steamboat_bill_ipod"),
    player: "video",
    collections: ["silent", "comedy", "classics"],
  },
  {
    id: "safety-last",
    title: "Safety Last!",
    tagline: "The clock.",
    synopsis:
      "Harold Lloyd hangs off a department-store clock in 1923 Los Angeles. The climb is real enough. The film is public domain.",
    year: 1923,
    runtimeMin: 73,
    rating: "G",
    kind: "film",
    origin: "public_domain",
    genres: ["comedy", "silent"],
    director: "Fred C. Newmeyer, Sam Taylor",
    cast: ["Harold Lloyd", "Mildred Davis"],
    poster: thumb("SafetyLastHaroldLloyd1923.FullMovieexcellentQuality."),
    backdrop: thumb("SafetyLastHaroldLloyd1923.FullMovieexcellentQuality."),
    playback: ia(
      "SafetyLastHaroldLloyd1923.FullMovieexcellentQuality.",
      "Safety Last - Harold Lloyd 1923. Full movie,excellent quality..mp4",
    ),
    archiveId: "SafetyLastHaroldLloyd1923.FullMovieexcellentQuality.",
    embedUrl: embed("SafetyLastHaroldLloyd1923.FullMovieexcellentQuality."),
    player: "video",
    collections: ["silent", "comedy", "classics"],
  },
  {
    id: "trip-moon",
    title: "A Trip to the Moon",
    tagline: "A rocket in the eye.",
    synopsis:
      "Georges Méliès, 1902. Scientists in pointed hats, a bullet to the moon, and the face that still means cinema. Public domain worldwide.",
    year: 1902,
    runtimeMin: 14,
    rating: "G",
    kind: "short",
    origin: "public_domain",
    genres: ["fantasy", "silent", "science fiction"],
    director: "Georges Méliès",
    cast: ["Georges Méliès"],
    poster: thumb("ATripToTheMoonGeorgeMelies"),
    backdrop: thumb("ATripToTheMoonGeorgeMelies"),
    playback: ia("ATripToTheMoonGeorgeMelies", "A Trip to the Moon-George Méliès.mp4"),
    archiveId: "ATripToTheMoonGeorgeMelies",
    embedUrl: embed("ATripToTheMoonGeorgeMelies"),
    player: "video",
    collections: ["silent", "shorts", "classics", "trending"],
  },
  {
    id: "phantom",
    title: "The Phantom of the Opera",
    tagline: "Beneath the Palais Garnier.",
    synopsis:
      "Lon Chaney, 1925. The unmasking, the chandelier, the underground lake. Universal's silent spectacle is in the U.S. public domain.",
    year: 1925,
    runtimeMin: 107,
    rating: "PG",
    kind: "film",
    origin: "public_domain",
    genres: ["horror", "silent", "romance"],
    director: "Rupert Julian",
    cast: ["Lon Chaney", "Mary Philbin", "Norman Kerry"],
    poster: thumb("ThePhantomOfTheOpera1925NewYorkGeneralReleasePrint_620"),
    backdrop: thumb("ThePhantomOfTheOpera1925NewYorkGeneralReleasePrint_620"),
    playback: ia(
      "ThePhantomOfTheOpera1925NewYorkGeneralReleasePrint_620",
      "ThePhantomOfTheOpera1925PublicDomainScore_512kb.mp4",
    ),
    archiveId: "ThePhantomOfTheOpera1925NewYorkGeneralReleasePrint_620",
    embedUrl: embed("ThePhantomOfTheOpera1925NewYorkGeneralReleasePrint_620"),
    player: "video",
    collections: ["silent", "horror", "classics", "tonight"],
  },
  {
    id: "movie-camera",
    title: "Man with a Movie Camera",
    tagline: "A city, cut to a heartbeat.",
    synopsis:
      "Dziga Vertov, 1929. Odessa, Kiev, Moscow — no actors, no intertitles, a camera that admits it is a camera. A public-domain manifesto of seeing.",
    year: 1929,
    runtimeMin: 68,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["documentary", "silent", "avant-garde"],
    director: "Dziga Vertov",
    cast: ["Mikhail Kaufman"],
    poster: thumb("ChelovekskinoapparatomManWithAMovieCamera"),
    backdrop: thumb("ChelovekskinoapparatomManWithAMovieCamera"),
    playback: ia("ChelovekskinoapparatomManWithAMovieCamera", "Chelovek_s_kino-apparatom_512kb.mp4"),
    archiveId: "ChelovekskinoapparatomManWithAMovieCamera",
    embedUrl: embed("ChelovekskinoapparatomManWithAMovieCamera"),
    player: "video",
    collections: ["silent", "classics"],
  },
  {
    id: "train-robbery",
    title: "The Great Train Robbery",
    tagline: "The pistol turns to you.",
    synopsis:
      "Edwin S. Porter, 1903. Fourteen minutes that taught American cinema about cross-cutting, pursuit, and looking down the barrel.",
    year: 1903,
    runtimeMin: 12,
    rating: "NR",
    kind: "short",
    origin: "public_domain",
    genres: ["western", "silent", "crime"],
    director: "Edwin S. Porter",
    cast: ["Justus D. Barnes", "Gilbert M. Anderson"],
    poster: thumb("TheGreatTrainRobbery1903"),
    backdrop: thumb("TheGreatTrainRobbery1903"),
    playback: ia("TheGreatTrainRobbery1903", "TheGreatTrainRobbery1903.mp4"),
    archiveId: "TheGreatTrainRobbery1903",
    embedUrl: embed("TheGreatTrainRobbery1903"),
    player: "video",
    collections: ["silent", "shorts", "classics"],
  },
  {
    id: "gertie",
    title: "Gertie the Dinosaur",
    tagline: "Winsor McCay draws her to life.",
    synopsis:
      "1914. A vaudeville cartoon that is also a contract with an animal. One of the first true animated characters, public domain.",
    year: 1914,
    runtimeMin: 12,
    rating: "G",
    kind: "short",
    origin: "public_domain",
    genres: ["animation", "silent"],
    director: "Winsor McCay",
    cast: ["Winsor McCay"],
    poster: thumb("Gertie"),
    backdrop: thumb("Gertie"),
    playback: ia("Gertie", "GertietheDinosaur.mp4"),
    archiveId: "Gertie",
    embedUrl: embed("Gertie"),
    player: "video",
    collections: ["silent", "shorts", "classics", "comedy", "new"],
  },
  {
    id: "his-girl-friday",
    title: "His Girl Friday",
    tagline: "A newspaper, a deadline, a remarriage.",
    synopsis:
      "Howard Hawks, 1940. Rosalind Russell and Cary Grant talk over each other at a speed that still feels modern. Released without a proper copyright notice — public domain.",
    year: 1940,
    runtimeMin: 92,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["comedy", "romance"],
    director: "Howard Hawks",
    cast: ["Cary Grant", "Rosalind Russell", "Ralph Bellamy"],
    poster: thumb("his_girl_friday"),
    backdrop: thumb("his_girl_friday"),
    playback: ia("his_girl_friday", "His Girl Friday.mp4"),
    archiveId: "his_girl_friday",
    embedUrl: embed("his_girl_friday"),
    player: "video",
    featured: true,
    badge: "Vault",
    collections: ["comedy", "classics", "trending", "tonight", "new"],
  },
  {
    id: "plan-9",
    title: "Plan 9 from Outer Space",
    tagline: "Future events such as these will affect you in the future.",
    synopsis:
      "Ed Wood, 1957. Cardboard tombs, stock footage, and a sincerity that cannot be faked. Public domain, and still the most honest bad picture in the vault.",
    year: 1957,
    runtimeMin: 79,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["science fiction", "horror"],
    director: "Edward D. Wood Jr.",
    cast: ["Bela Lugosi", "Vampira", "Tor Johnson"],
    poster: thumb("Plan_9_from_Outer_Space_1959"),
    backdrop: thumb("Plan_9_from_Outer_Space_1959"),
    playback: ia("Plan_9_from_Outer_Space_1959", "Plan9FromOuterSpace.mp4"),
    archiveId: "Plan_9_from_Outer_Space_1959",
    embedUrl: embed("Plan_9_from_Outer_Space_1959"),
    player: "video",
    collections: ["horror", "classics", "new"],
  },
  {
    id: "metropolis",
    title: "Metropolis",
    tagline: "The mediator between head and hands must be the heart.",
    synopsis:
      "Fritz Lang, 1927. A machine-city, a false Maria, and the most expensive silent film of its decade. U.S. public domain.",
    year: 1927,
    runtimeMin: 153,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["silent", "science fiction"],
    director: "Fritz Lang",
    cast: ["Brigitte Helm", "Gustav Fröhlich", "Rudolf Klein-Rogge"],
    poster: thumb("metropolis-1927-restored-version-2010"),
    backdrop: thumb("metropolis-1927-restored-version-2010"),
    playback: ia("metropolis-1927-restored-version-2010", "Metropolis (1927).mp4"),
    archiveId: "metropolis-1927-restored-version-2010",
    embedUrl: embed("metropolis-1927-restored-version-2010"),
    player: "video",
    collections: ["silent", "classics", "trending", "new", "expressionist"],
  },
  {
    id: "stranger",
    title: "The Stranger",
    tagline: "A clock tower in Connecticut.",
    synopsis:
      "Orson Welles, 1946. A war-crimes investigator follows a man who should not be teaching in a New England town. Public domain.",
    year: 1946,
    runtimeMin: 95,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["noir", "thriller"],
    director: "Orson Welles",
    cast: ["Orson Welles", "Edward G. Robinson", "Loretta Young"],
    poster: thumb("TheStranger"),
    backdrop: thumb("TheStranger"),
    playback: ia("TheStranger", "The_Stranger.mp4"),
    archiveId: "TheStranger",
    embedUrl: embed("TheStranger"),
    player: "video",
    collections: ["noir", "classics", "new"],
  },
  {
    id: "dangerous-game",
    title: "The Most Dangerous Game",
    tagline: "The hunter has a new animal.",
    synopsis:
      "1932. Shipwreck, island, a count who hunts men. A pre-code thriller that still runs on a clock, now in the public domain.",
    year: 1932,
    runtimeMin: 63,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["thriller", "horror"],
    director: "Irving Pichel, Ernest B. Schoedsack",
    cast: ["Joel McCrea", "Fay Wray", "Leslie Banks"],
    poster: thumb("TheMostDangerousGame"),
    backdrop: thumb("TheMostDangerousGame"),
    playback: ia("TheMostDangerousGame", "TheMostDangerousGame.mp4"),
    archiveId: "TheMostDangerousGame",
    embedUrl: embed("TheMostDangerousGame"),
    player: "video",
    collections: ["horror", "classics", "trending", "new", "precode"],
  },
  {
    id: "intolerance",
    title: "Intolerance",
    tagline: "Four centuries, one cut.",
    synopsis:
      "D. W. Griffith, 1916. Babylon, Judea, France, a modern slum — cross-cut until history itself looks like montage. Public domain.",
    year: 1916,
    runtimeMin: 197,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["silent", "drama"],
    director: "D. W. Griffith",
    cast: ["Constance Talmadge", "Mae Marsh", "Robert Harron"],
    poster: thumb("Intolerance"),
    backdrop: thumb("Intolerance"),
    playback: ia("Intolerance", "Intolerance.mp4"),
    archiveId: "Intolerance",
    embedUrl: embed("Intolerance"),
    player: "video",
    collections: ["silent", "classics", "new"],
  },
  {
    id: "potemkin",
    title: "Battleship Potemkin",
    tagline: "The Odessa steps.",
    synopsis:
      "Sergei Eisenstein, 1925. A mutiny, a massacre cut into fragments, and the textbook on montage. Public domain in the United States.",
    year: 1925,
    runtimeMin: 75,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["silent", "drama"],
    director: "Sergei Eisenstein",
    cast: ["Aleksandr Antonov", "Vladimir Barsky"],
    poster: thumb("BattleshipPotemkin"),
    backdrop: thumb("BattleshipPotemkin"),
    playback: ia("BattleshipPotemkin", "BattleshipPotemkin.mp4"),
    archiveId: "BattleshipPotemkin",
    embedUrl: embed("BattleshipPotemkin"),
    player: "video",
    collections: ["silent", "classics", "new"],
  },
  {
    id: "the-kid",
    title: "The Kid",
    tagline: "A tramp, a child, a window.",
    synopsis:
      "Charlie Chaplin, 1921. His first feature. Jackie Coogan as the kid. Pathos without permission, and in the U.S. public domain.",
    year: 1921,
    runtimeMin: 68,
    rating: "G",
    kind: "film",
    origin: "public_domain",
    genres: ["comedy", "silent", "drama"],
    director: "Charlie Chaplin",
    cast: ["Charlie Chaplin", "Jackie Coogan", "Edna Purviance"],
    poster: thumb("TheKid1921"),
    backdrop: thumb("TheKid1921"),
    playback: ia("TheKid1921", "The Kid (1921).mp4"),
    archiveId: "TheKid1921",
    embedUrl: embed("TheKid1921"),
    player: "video",
    collections: ["silent", "comedy", "classics", "new"],
  },
  {
    id: "brain-die",
    title: "The Brain That Wouldn't Die",
    tagline: "A head in a pan, a man in a lab.",
    synopsis:
      "1962. A surgeon keeps his fiancée's head alive and goes shopping for a body. Public-domain drive-in science, later a cult object.",
    year: 1962,
    runtimeMin: 82,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["horror", "science fiction"],
    director: "Joseph Green",
    cast: ["Jason Evers", "Virginia Leith"],
    poster: thumb("TheBrainThatWouldntDie"),
    backdrop: thumb("TheBrainThatWouldntDie"),
    playback: ia("TheBrainThatWouldntDie", "The Brain That Wouldn't Die.mp4"),
    archiveId: "TheBrainThatWouldntDie",
    embedUrl: embed("TheBrainThatWouldntDie"),
    player: "video",
    collections: ["horror", "classics", "new"],
  },
  {
    id: "meet-john-doe",
    title: "Meet John Doe",
    tagline: "A man who never existed becomes the country's conscience.",
    synopsis:
      "Frank Capra, 1941. Gary Cooper as a drifter hired to play a fictional everyman whose suicide note wakes a nation. A Capra picture that lapsed into the public domain.",
    year: 1941,
    runtimeMin: 122,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["drama", "romance"],
    director: "Frank Capra",
    cast: ["Gary Cooper", "Barbara Stanwyck", "Edward Arnold"],
    poster: thumb("meet_john_doe"),
    backdrop: thumb("meet_john_doe"),
    playback: ia("meet_john_doe", "Meet_John_Doe.mp4"),
    archiveId: "meet_john_doe",
    embedUrl: embed("meet_john_doe"),
    player: "video",
    collections: ["classics", "trending"],
  },
  {
    id: "lost-world",
    title: "The Lost World",
    tagline: "Dinosaurs on the plateau, and then in London.",
    synopsis:
      "Harry O. Hoyt, 1925. Willis O'Brien's stop-motion animals walk a South American plateau years before Kong. Public domain, and still the template for a lost world.",
    year: 1925,
    runtimeMin: 64,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["adventure", "silent", "science fiction"],
    director: "Harry O. Hoyt",
    cast: ["Bessie Love", "Lewis Stone", "Wallace Beery"],
    poster: thumb("TheLostWorld1925"),
    backdrop: thumb("TheLostWorld1925"),
    playback: ia("TheLostWorld1925", "TheLostWorld1925.mp4"),
    archiveId: "TheLostWorld1925",
    embedUrl: embed("TheLostWorld1925"),
    player: "video",
    collections: ["silent", "classics", "new"],
  },
  {
    id: "gold-rush",
    title: "The Gold Rush",
    tagline: "A cabin, a storm, a dance of rolls.",
    synopsis:
      "Charlie Chaplin, 1925. The Tramp in the Klondike: starvation, a dance of bread rolls, and a house teetering on a cliff. The 1925 silent cut is in the U.S. public domain.",
    year: 1925,
    runtimeMin: 95,
    rating: "G",
    kind: "film",
    origin: "public_domain",
    genres: ["comedy", "silent", "drama"],
    director: "Charlie Chaplin",
    cast: ["Charlie Chaplin", "Georgia Hale", "Mack Swain"],
    poster: thumb("TheGoldRush1925"),
    backdrop: thumb("TheGoldRush1925"),
    playback: ia("TheGoldRush1925", "TheGoldRush1925.mp4"),
    archiveId: "TheGoldRush1925",
    embedUrl: embed("TheGoldRush1925"),
    player: "video",
    featured: true,
    collections: ["silent", "comedy", "classics", "trending", "new"],
  },
  {
    id: "nanook",
    title: "Nanook of the North",
    tagline: "A family, an ice floe, a camera that would not leave.",
    synopsis:
      "Robert J. Flaherty, 1922. Often called the first feature documentary: staged in places, true in others, and a foundation of ethnographic cinema. Public domain.",
    year: 1922,
    runtimeMin: 79,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["documentary", "silent"],
    director: "Robert J. Flaherty",
    cast: ["Allakariallak", "Nyla"],
    poster: thumb("NanookOfTheNorth1922"),
    backdrop: thumb("NanookOfTheNorth1922"),
    playback: ia("NanookOfTheNorth1922", "NanookOfTheNorth.mp4"),
    archiveId: "NanookOfTheNorth1922",
    embedUrl: embed("NanookOfTheNorth1922"),
    player: "video",
    collections: ["silent", "classics"],
  },
  {
    id: "haxan",
    title: "Häxan",
    tagline: "Witchcraft through the ages.",
    synopsis:
      "Benjamin Christensen, 1922. A lecture that becomes a sabbath. One of the strangest silent films still in circulation, and in the public domain.",
    year: 1922,
    runtimeMin: 105,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["horror", "silent", "documentary"],
    director: "Benjamin Christensen",
    cast: ["Benjamin Christensen", "Maren Pedersen"],
    poster: thumb("Haxan1922"),
    backdrop: thumb("Haxan1922"),
    playback: ia("Haxan1922", "Haxan.mp4"),
    archiveId: "Haxan1922",
    embedUrl: embed("Haxan1922"),
    player: "video",
    collections: ["silent", "horror", "classics"],
  },
  {
    id: "faust",
    title: "Faust",
    tagline: "A pact, a plague, a flight over the town.",
    synopsis:
      "F. W. Murnau, 1926. Mephisto blankets a village; Faust sells a soul; the camera learns to fly. U.S. public domain.",
    year: 1926,
    runtimeMin: 107,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["silent", "fantasy", "horror"],
    director: "F. W. Murnau",
    cast: ["Gösta Ekman", "Emil Jannings", "Camilla Horn"],
    poster: thumb("Faust1926Murnau"),
    backdrop: thumb("Faust1926Murnau"),
    playback: ia("Faust1926Murnau", "Faust1926.mp4"),
    archiveId: "Faust1926Murnau",
    embedUrl: embed("Faust1926Murnau"),
    player: "video",
    collections: ["silent", "horror", "classics", "new", "expressionist"],
  },
  {
    id: "sunrise",
    title: "Sunrise",
    tagline: "A song of two humans.",
    synopsis:
      "F. W. Murnau, 1927. A farmer, a city woman, a wife, and the most liquid camera of the silent years. Entered the U.S. public domain in 2023.",
    year: 1927,
    runtimeMin: 94,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["silent", "drama", "romance"],
    director: "F. W. Murnau",
    cast: ["George O'Brien", "Janet Gaynor", "Margaret Livingston"],
    poster: thumb("Sunrise1927"),
    backdrop: thumb("Sunrise1927"),
    playback: ia("Sunrise1927", "Sunrise1927.mp4"),
    archiveId: "Sunrise1927",
    embedUrl: embed("Sunrise1927"),
    player: "video",
    featured: true,
    collections: ["silent", "classics", "trending", "new"],
  },
  {
    id: "joan-of-arc",
    title: "The Passion of Joan of Arc",
    tagline: "A face, a trial, a cut.",
    synopsis:
      "Carl Theodor Dreyer, 1928. Maria Falconetti's face is the film. Interrogation as montage. U.S. public domain.",
    year: 1928,
    runtimeMin: 82,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["silent", "drama"],
    director: "Carl Theodor Dreyer",
    cast: ["Maria Falconetti", "Eugène Silvain"],
    poster: thumb("ThePassionOfJoanOfArc"),
    backdrop: thumb("ThePassionOfJoanOfArc"),
    playback: ia("ThePassionOfJoanOfArc", "ThePassionOfJoanOfArc.mp4"),
    archiveId: "ThePassionOfJoanOfArc",
    embedUrl: embed("ThePassionOfJoanOfArc"),
    player: "video",
    collections: ["silent", "classics", "trending"],
  },
  {
    id: "chien-andalou",
    title: "Un Chien Andalou",
    tagline: "Sixteen minutes that still startle.",
    synopsis:
      "Luis Buñuel and Salvador Dalí, 1929. A razor, a cloud, an eye. The short that taught the avant-garde it could cut like a dream. Public domain.",
    year: 1929,
    runtimeMin: 16,
    rating: "NR",
    kind: "short",
    origin: "public_domain",
    genres: ["silent", "avant-garde"],
    director: "Luis Buñuel",
    cast: ["Simone Mareuil", "Pierre Batcheff"],
    poster: thumb("UnChienAndalou"),
    backdrop: thumb("UnChienAndalou"),
    playback: ia("UnChienAndalou", "UnChienAndalou.mp4"),
    archiveId: "UnChienAndalou",
    embedUrl: embed("UnChienAndalou"),
    player: "video",
    collections: ["silent", "shorts", "classics"],
  },
  {
    id: "one-week",
    title: "One Week",
    tagline: "A house built in the wrong order.",
    synopsis:
      "Buster Keaton, 1920. A prefab house, a jealous suitor, a train. Nineteen minutes of construction as slapstick. Public domain.",
    year: 1920,
    runtimeMin: 19,
    rating: "G",
    kind: "short",
    origin: "public_domain",
    genres: ["comedy", "silent"],
    director: "Buster Keaton, Edward F. Cline",
    cast: ["Buster Keaton", "Sybil Seely"],
    poster: thumb("OneWeek1920"),
    backdrop: thumb("OneWeek1920"),
    playback: ia("OneWeek1920", "OneWeek1920.mp4"),
    archiveId: "OneWeek1920",
    embedUrl: embed("OneWeek1920"),
    player: "video",
    collections: ["silent", "comedy", "shorts", "classics", "new"],
  },
  {
    id: "reefer",
    title: "Reefer Madness",
    tagline: "Tell your children.",
    synopsis:
      "1936 exploitation that became a midnight joke: a lecture on marijuana that cannot keep a straight face. Public domain, and a period document more than a film.",
    year: 1936,
    runtimeMin: 66,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["drama", "exploitation"],
    director: "Louis J. Gasnier",
    cast: ["Dorothy Short", "Kenneth Craig"],
    poster: thumb("ReeferMadness"),
    backdrop: thumb("ReeferMadness"),
    playback: ia("ReeferMadness", "ReeferMadness.mp4"),
    archiveId: "ReeferMadness",
    embedUrl: embed("ReeferMadness"),
    player: "video",
    collections: ["classics"],
  },
  {
    id: "salt-earth",
    title: "Salt of the Earth",
    tagline: "A strike, a blacklist, a picture they tried to bury.",
    synopsis:
      "Herbert J. Biberman, 1954. New Mexico zinc miners and the women who hold the line. Made by blacklisted artists, suppressed on release, now public domain.",
    year: 1954,
    runtimeMin: 94,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["drama", "documentary"],
    director: "Herbert J. Biberman",
    cast: ["Rosaura Revueltas", "Juan Chacón"],
    poster: thumb("SaltOfTheEarth"),
    backdrop: thumb("SaltOfTheEarth"),
    playback: ia("SaltOfTheEarth", "SaltOfTheEarth.mp4"),
    archiveId: "SaltOfTheEarth",
    embedUrl: embed("SaltOfTheEarth"),
    player: "video",
    collections: ["classics", "new"],
  },
  {
    id: "big-combo",
    title: "The Big Combo",
    tagline: "A cop, a syndicate, a spotlight in the fog.",
    synopsis:
      "Joseph H. Lewis, 1955. John Alton photographs a crime syndicate as if the dark itself were a character. A public-domain noir with a jazz pulse.",
    year: 1955,
    runtimeMin: 89,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["noir", "crime", "thriller"],
    director: "Joseph H. Lewis",
    cast: ["Cornel Wilde", "Richard Conte", "Jean Wallace"],
    poster: thumb("TheBigCombo"),
    backdrop: thumb("TheBigCombo"),
    playback: ia("TheBigCombo", "TheBigCombo.mp4"),
    archiveId: "TheBigCombo",
    embedUrl: embed("TheBigCombo"),
    player: "video",
    collections: ["noir", "classics", "trending", "new"],
  },
  {
    id: "he-walked",
    title: "He Walked by Night",
    tagline: "A cop-killer in the storm drains.",
    synopsis:
      "1948. Semi-documentary noir: a technician who knows the city's pipes, a dragnet, and Los Angeles photographed like evidence. Public domain.",
    year: 1948,
    runtimeMin: 79,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["noir", "crime", "thriller"],
    director: "Alfred L. Werker",
    cast: ["Richard Basehart", "Scott Brady", "Jack Webb"],
    poster: thumb("HeWalkedByNight"),
    backdrop: thumb("HeWalkedByNight"),
    playback: ia("HeWalkedByNight", "HeWalkedByNight.mp4"),
    archiveId: "HeWalkedByNight",
    embedUrl: embed("HeWalkedByNight"),
    player: "video",
    collections: ["noir", "classics"],
  },
  {
    id: "mclintock",
    title: "McLintock!",
    tagline: "A cattle baron, a mud pit, a returning wife.",
    synopsis:
      "Andrew V. McLaglen, 1963. John Wayne and Maureen O'Hara in a frontier comedy that lapsed into the public domain — a rare late studio picture in the vault.",
    year: 1963,
    runtimeMin: 127,
    rating: "NR",
    kind: "film",
    origin: "public_domain",
    genres: ["western", "comedy"],
    director: "Andrew V. McLaglen",
    cast: ["John Wayne", "Maureen O'Hara", "Stefanie Powers"],
    poster: thumb("McLintock"),
    backdrop: thumb("McLintock"),
    playback: ia("McLintock", "McLintock.mp4"),
    archiveId: "McLintock",
    embedUrl: embed("McLintock"),
    player: "video",
    collections: ["comedy", "classics", "new"],
  },
];

export function getTitle(id: string) {
  return STREAM_CATALOG.find((t) => t.id === id);
}

export function titlesIn(collection: string) {
  return STREAM_CATALOG.filter((t) => t.collections.includes(collection));
}

export function searchTitles(q: string) {
  const n = q.trim().toLowerCase();
  if (!n) return [];
  return STREAM_CATALOG.filter((t) => {
    const blob = [
      t.title,
      t.tagline,
      t.synopsis,
      t.director,
      t.genres.join(" "),
      t.cast.join(" "),
      String(t.year),
      t.rating,
    ]
      .join(" ")
      .toLowerCase();
    return blob.includes(n);
  });
}

export function similarTo(title: StreamTitle, limit = 8) {
  return STREAM_CATALOG.filter((t) => t.id !== title.id)
    .map((t) => {
      const sharedGenres = t.genres.filter((g) => title.genres.includes(g)).length;
      const sameDirector =
        t.director === title.director ||
        t.director.split(/,| & /).some((n) => title.director.includes(n.trim()) && n.trim().length > 3);
      return {
        t,
        score:
          sharedGenres * 3 +
          (sameDirector ? 5 : 0) +
          (t.origin === title.origin ? 1 : 0) +
          (t.kind === title.kind ? 1 : 0) +
          (Math.abs(t.year - title.year) <= 10 ? 1 : 0),
      };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((x) => x.t);
}

export function featuredTitles() {
  return STREAM_CATALOG.filter((t) => t.featured);
}

export function comingSoonTitles() {
  return STREAM_CATALOG.filter((t) => t.comingSoon);
}

export function playableTitles() {
  return STREAM_CATALOG.filter((t) => t.player !== "none" && !t.comingSoon);
}

export function allGenres() {
  return [...new Set(STREAM_CATALOG.flatMap((t) => t.genres))].sort();
}

export function titlesForRow(rowId: string) {
  if (rowId === "precode") {
    const tagged = titlesIn("precode");
    const byYear = STREAM_CATALOG.filter(
      (t) => t.origin === "public_domain" && t.year >= 1929 && t.year <= 1934,
    );
    const ids = new Set(tagged.map((t) => t.id));
    return [...tagged, ...byYear.filter((t) => !ids.has(t.id))];
  }
  if (rowId === "top10") {
    return playableTitles()
      .map((t) => ({
        t,
        score:
          (t.featured ? 8 : 0) +
          (t.collections.includes("trending") ? 5 : 0) +
          (t.origin === "original" && !t.comingSoon ? 4 : 0) +
          (t.collections.includes("tonight") ? 2 : 0) +
          (t.runtimeMin >= 60 ? 1 : 0),
      }))
      .sort((a, b) => b.score - a.score || a.t.title.localeCompare(b.t.title))
      .slice(0, 10)
      .map((x) => x.t);
  }
  const decade = /^(\d{4})s$/.exec(rowId);
  if (decade) {
    const start = Number(decade[1]);
    return STREAM_CATALOG.filter((t) => t.year >= start && t.year < start + 10);
  }
  const inCol = titlesIn(rowId);
  if (inCol.length) return inCol;
  return STREAM_CATALOG.filter(
    (t) => t.genres.includes(rowId) || t.origin === rowId || t.kind === rowId,
  );
}

export function rowMeta(rowId: string) {
  return STREAM_ROWS.find((r) => r.id === rowId);
}

export function canPlay(title: StreamTitle) {
  return title.player !== "none" && !title.comingSoon;
}

