/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibleRouteImport } from './routes/bible'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as WatchIndexRouteImport } from './routes/watch.index'
import { Route as WatchAboutRouteImport } from './routes/watch.about'
import { Route as WatchCatalogRouteImport } from './routes/watch.catalog'
import { Route as WatchComingSoonRouteImport } from './routes/watch.coming-soon'
import { Route as WatchHelpRouteImport } from './routes/watch.help'
import { Route as WatchHistoryRouteImport } from './routes/watch.history'
import { Route as WatchMyListRouteImport } from './routes/watch.my-list'
import { Route as WatchPeopleRouteImport } from './routes/watch.people'
import { Route as WatchSearchRouteImport } from './routes/watch.search'
import { Route as WatchSurpriseRouteImport } from './routes/watch.surprise'
import { Route as WatchBrowseRowRouteImport } from './routes/watch.browse.$row'
import { Route as WatchPeopleIndexRouteImport } from './routes/watch.people.index'
import { Route as WatchPeopleSlugRouteImport } from './routes/watch.people.$slug'
import { Route as WatchPlayTitleIdRouteImport } from './routes/watch.play.$titleId'
import { Route as WatchTitleTitleIdRouteImport } from './routes/watch.title.$titleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRoute = BibleRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WatchRoute,
} as any)
const WatchAboutRoute = WatchAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => WatchRoute,
} as any)
const WatchCatalogRoute = WatchCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => WatchRoute,
} as any)
const WatchComingSoonRoute = WatchComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => WatchRoute,
} as any)
const WatchHelpRoute = WatchHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => WatchRoute,
} as any)
const WatchHistoryRoute = WatchHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => WatchRoute,
} as any)
const WatchMyListRoute = WatchMyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => WatchRoute,
} as any)
const WatchPeopleRoute = WatchPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => WatchRoute,
} as any)
const WatchSearchRoute = WatchSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => WatchRoute,
} as any)
const WatchSurpriseRoute = WatchSurpriseRouteImport.update({
  id: '/surprise',
  path: '/surprise',
  getParentRoute: () => WatchRoute,
} as any)
const WatchBrowseRowRoute = WatchBrowseRowRouteImport.update({
  id: '/browse/$row',
  path: '/browse/$row',
  getParentRoute: () => WatchRoute,
} as any)
const WatchPeopleIndexRoute = WatchPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WatchPeopleRoute,
} as any)
const WatchPeopleSlugRoute = WatchPeopleSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WatchPeopleRoute,
} as any)
const WatchPlayTitleIdRoute = WatchPlayTitleIdRouteImport.update({
  id: '/play/$titleId',
  path: '/play/$titleId',
  getParentRoute: () => WatchRoute,
} as any)
const WatchTitleTitleIdRoute = WatchTitleTitleIdRouteImport.update({
  id: '/title/$titleId',
  path: '/title/$titleId',
  getParentRoute: () => WatchRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/ingest': typeof IngestRoute
  '/pipeline': typeof PipelineRoute
  '/watch': typeof WatchRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/watch/about': typeof WatchAboutRoute
  '/watch/catalog': typeof WatchCatalogRoute
  '/watch/coming-soon': typeof WatchComingSoonRoute
  '/watch/help': typeof WatchHelpRoute
  '/watch/history': typeof WatchHistoryRoute
  '/watch/my-list': typeof WatchMyListRoute
  '/watch/people': typeof WatchPeopleRouteWithChildren
  '/watch/search': typeof WatchSearchRoute
  '/watch/surprise': typeof WatchSurpriseRoute
  '/watch/': typeof WatchIndexRoute
  '/watch/browse/$row': typeof WatchBrowseRowRoute
  '/watch/people/$slug': typeof WatchPeopleSlugRoute
  '/watch/play/$titleId': typeof WatchPlayTitleIdRoute
  '/watch/title/$titleId': typeof WatchTitleTitleIdRoute
  '/watch/people/': typeof WatchPeopleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/ingest': typeof IngestRoute
  '/pipeline': typeof PipelineRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/watch/about': typeof WatchAboutRoute
  '/watch/catalog': typeof WatchCatalogRoute
  '/watch/coming-soon': typeof WatchComingSoonRoute
  '/watch/help': typeof WatchHelpRoute
  '/watch/history': typeof WatchHistoryRoute
  '/watch/my-list': typeof WatchMyListRoute
  '/watch/search': typeof WatchSearchRoute
  '/watch/surprise': typeof WatchSurpriseRoute
  '/watch': typeof WatchIndexRoute
  '/watch/browse/$row': typeof WatchBrowseRowRoute
  '/watch/people/$slug': typeof WatchPeopleSlugRoute
  '/watch/play/$titleId': typeof WatchPlayTitleIdRoute
  '/watch/title/$titleId': typeof WatchTitleTitleIdRoute
  '/watch/people': typeof WatchPeopleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bible': typeof BibleRoute
  '/ingest': typeof IngestRoute
  '/pipeline': typeof PipelineRoute
  '/watch': typeof WatchRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/watch/about': typeof WatchAboutRoute
  '/watch/catalog': typeof WatchCatalogRoute
  '/watch/coming-soon': typeof WatchComingSoonRoute
  '/watch/help': typeof WatchHelpRoute
  '/watch/history': typeof WatchHistoryRoute
  '/watch/my-list': typeof WatchMyListRoute
  '/watch/people': typeof WatchPeopleRouteWithChildren
  '/watch/search': typeof WatchSearchRoute
  '/watch/surprise': typeof WatchSurpriseRoute
  '/watch/': typeof WatchIndexRoute
  '/watch/browse/$row': typeof WatchBrowseRowRoute
  '/watch/people/$slug': typeof WatchPeopleSlugRoute
  '/watch/play/$titleId': typeof WatchPlayTitleIdRoute
  '/watch/title/$titleId': typeof WatchTitleTitleIdRoute
  '/watch/people/': typeof WatchPeopleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bible'
    | '/ingest'
    | '/pipeline'
    | '/watch'
    | '/jobs/$jobId'
    | '/watch/about'
    | '/watch/catalog'
    | '/watch/coming-soon'
    | '/watch/help'
    | '/watch/history'
    | '/watch/my-list'
    | '/watch/people'
    | '/watch/search'
    | '/watch/surprise'
    | '/watch/'
    | '/watch/browse/$row'
    | '/watch/people/$slug'
    | '/watch/play/$titleId'
    | '/watch/title/$titleId'
    | '/watch/people/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bible'
    | '/ingest'
    | '/pipeline'
    | '/jobs/$jobId'
    | '/watch/about'
    | '/watch/catalog'
    | '/watch/coming-soon'
    | '/watch/help'
    | '/watch/history'
    | '/watch/my-list'
    | '/watch/search'
    | '/watch/surprise'
    | '/watch'
    | '/watch/browse/$row'
    | '/watch/people/$slug'
    | '/watch/play/$titleId'
    | '/watch/title/$titleId'
    | '/watch/people'
  id:
    | '__root__'
    | '/'
    | '/bible'
    | '/ingest'
    | '/pipeline'
    | '/watch'
    | '/jobs/$jobId'
    | '/watch/about'
    | '/watch/catalog'
    | '/watch/coming-soon'
    | '/watch/help'
    | '/watch/history'
    | '/watch/my-list'
    | '/watch/people'
    | '/watch/search'
    | '/watch/surprise'
    | '/watch/'
    | '/watch/browse/$row'
    | '/watch/people/$slug'
    | '/watch/play/$titleId'
    | '/watch/title/$titleId'
    | '/watch/people/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibleRoute: typeof BibleRoute
  IngestRoute: typeof IngestRoute
  PipelineRoute: typeof PipelineRoute
  WatchRoute: typeof WatchRouteWithChildren
  JobsJobIdRoute: typeof JobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/': {
      id: '/watch/'
      path: '/'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/about': {
      id: '/watch/about'
      path: '/about'
      fullPath: '/watch/about'
      preLoaderRoute: typeof WatchAboutRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/catalog': {
      id: '/watch/catalog'
      path: '/catalog'
      fullPath: '/watch/catalog'
      preLoaderRoute: typeof WatchCatalogRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/coming-soon': {
      id: '/watch/coming-soon'
      path: '/coming-soon'
      fullPath: '/watch/coming-soon'
      preLoaderRoute: typeof WatchComingSoonRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/help': {
      id: '/watch/help'
      path: '/help'
      fullPath: '/watch/help'
      preLoaderRoute: typeof WatchHelpRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/history': {
      id: '/watch/history'
      path: '/history'
      fullPath: '/watch/history'
      preLoaderRoute: typeof WatchHistoryRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/my-list': {
      id: '/watch/my-list'
      path: '/my-list'
      fullPath: '/watch/my-list'
      preLoaderRoute: typeof WatchMyListRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/people': {
      id: '/watch/people'
      path: '/people'
      fullPath: '/watch/people'
      preLoaderRoute: typeof WatchPeopleRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/search': {
      id: '/watch/search'
      path: '/search'
      fullPath: '/watch/search'
      preLoaderRoute: typeof WatchSearchRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/surprise': {
      id: '/watch/surprise'
      path: '/surprise'
      fullPath: '/watch/surprise'
      preLoaderRoute: typeof WatchSurpriseRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/browse/$row': {
      id: '/watch/browse/$row'
      path: '/browse/$row'
      fullPath: '/watch/browse/$row'
      preLoaderRoute: typeof WatchBrowseRowRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/people/': {
      id: '/watch/people/'
      path: '/'
      fullPath: '/watch/people/'
      preLoaderRoute: typeof WatchPeopleIndexRouteImport
      parentRoute: typeof WatchPeopleRoute
    }
    '/watch/people/$slug': {
      id: '/watch/people/$slug'
      path: '/$slug'
      fullPath: '/watch/people/$slug'
      preLoaderRoute: typeof WatchPeopleSlugRouteImport
      parentRoute: typeof WatchPeopleRoute
    }
    '/watch/play/$titleId': {
      id: '/watch/play/$titleId'
      path: '/play/$titleId'
      fullPath: '/watch/play/$titleId'
      preLoaderRoute: typeof WatchPlayTitleIdRouteImport
      parentRoute: typeof WatchRoute
    }
    '/watch/title/$titleId': {
      id: '/watch/title/$titleId'
      path: '/title/$titleId'
      fullPath: '/watch/title/$titleId'
      preLoaderRoute: typeof WatchTitleTitleIdRouteImport
      parentRoute: typeof WatchRoute
    }
  }
}

interface WatchPeopleRouteChildren {
  WatchPeopleSlugRoute: typeof WatchPeopleSlugRoute
  WatchPeopleIndexRoute: typeof WatchPeopleIndexRoute
}

const WatchPeopleRouteChildren: WatchPeopleRouteChildren = {
  WatchPeopleSlugRoute: WatchPeopleSlugRoute,
  WatchPeopleIndexRoute: WatchPeopleIndexRoute,
}

const WatchPeopleRouteWithChildren = WatchPeopleRoute._addFileChildren(
  WatchPeopleRouteChildren,
)

interface WatchRouteChildren {
  WatchAboutRoute: typeof WatchAboutRoute
  WatchCatalogRoute: typeof WatchCatalogRoute
  WatchComingSoonRoute: typeof WatchComingSoonRoute
  WatchHelpRoute: typeof WatchHelpRoute
  WatchHistoryRoute: typeof WatchHistoryRoute
  WatchMyListRoute: typeof WatchMyListRoute
  WatchPeopleRoute: typeof WatchPeopleRouteWithChildren
  WatchSearchRoute: typeof WatchSearchRoute
  WatchSurpriseRoute: typeof WatchSurpriseRoute
  WatchIndexRoute: typeof WatchIndexRoute
  WatchBrowseRowRoute: typeof WatchBrowseRowRoute
  WatchPlayTitleIdRoute: typeof WatchPlayTitleIdRoute
  WatchTitleTitleIdRoute: typeof WatchTitleTitleIdRoute
}

const WatchRouteChildren: WatchRouteChildren = {
  WatchAboutRoute: WatchAboutRoute,
  WatchCatalogRoute: WatchCatalogRoute,
  WatchComingSoonRoute: WatchComingSoonRoute,
  WatchHelpRoute: WatchHelpRoute,
  WatchHistoryRoute: WatchHistoryRoute,
  WatchMyListRoute: WatchMyListRoute,
  WatchPeopleRoute: WatchPeopleRouteWithChildren,
  WatchSearchRoute: WatchSearchRoute,
  WatchSurpriseRoute: WatchSurpriseRoute,
  WatchIndexRoute: WatchIndexRoute,
  WatchBrowseRowRoute: WatchBrowseRowRoute,
  WatchPlayTitleIdRoute: WatchPlayTitleIdRoute,
  WatchTitleTitleIdRoute: WatchTitleTitleIdRoute,
}

const WatchRouteWithChildren = WatchRoute._addFileChildren(WatchRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibleRoute: BibleRoute,
  IngestRoute: IngestRoute,
  PipelineRoute: PipelineRoute,
  WatchRoute: WatchRouteWithChildren,
  JobsJobIdRoute: JobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
